sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=terraform:S6329
sonar.issue.ignore.multicriteria.e1.resourceKey=infrastructure/terraform/modules/compute/main.tf
sonar.exclusions=infrastructure/terraform/modules/compute/main.tf
