server {
    listen 80;
    server_name equitylens.co.za www.equitylens.co.za;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name equitylens.co.za www.equitylens.co.za;

    ssl_certificate /etc/letsencrypt/live/equitylens.co.za/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/equitylens.co.za/privkey.pem;

    add_header X-content-Type-options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Cross-Origin-Resource-Policy "same-site" always;
    server_tokens off;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name api.equitylens.co.za;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.equitylens.co.za;

    ssl_certificate /etc/letsencrypt/live/equitylens.co.za/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/equitylens.co.za/privkey.pem;

    add_header X-content-Type-options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Cross-Origin-Resource-Policy "same-site" always;
    server_tokens off;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
