name: CI 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    backend:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: just to run
              run: echo "Will be empty for now"
    