name: CI 

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  id-token: write

jobs:
    backend:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: To checkout the repository
              uses: actions/checkout@v4

            - name: To install all python package for backend
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install all the backend dependencies
              working-directory: backend
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run all the backend tests
              working-directory: backend
              run: pytest

            - name: To Build backend Docker image
              run: docker build -t equity-lens-backend ./backend

            - name: To make the Configure AWS credentials
              if: github.event_name == 'pull_request'
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ vars.AWS_REGION }}

            - name: To Log in to Amazon ECR
              if: github.event_name == 'pull_request'
              id: login-to-store-credentials
              uses: aws-actions/amazon-ecr-login@v2

            - name: To make a tag and to also push all the backend and all the image from the docker to Amazon ECR
              if: github.event_name == 'pull_request'
              env:
                TO_STORE_THE_ECR_REGISTRY: ${{ steps.login-to-store-credentials.outputs.registry }}
                TO_STORE_THE_ECR_REPOSITORY: ${{ vars.BACKEND_ECR_REPOSITORY }}
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker tag equity-lens-backend $TO_STORE_THE_ECR_REGISTRY/$TO_STORE_THE_ECR_REPOSITORY:$IMAGE_TAG
                docker tag equity-lens-backend $TO_STORE_THE_ECR_REGISTRY/$TO_STORE_THE_ECR_REPOSITORY:latest

                docker push $TO_STORE_THE_ECR_REGISTRY/$TO_STORE_THE_ECR_REPOSITORY:$IMAGE_TAG
                docker push $TO_STORE_THE_ECR_REGISTRY/$TO_STORE_THE_ECR_REPOSITORY:latest

            - name: to automatically deploy the backed to the EC2
              if: github.event_name == 'pull_request'
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_PUBLIC_ADDRESS}}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.THE_PRIVATE_SSH_KEY }}
                script: |
                  set -e

                  aws ecr get-login-password --region ${{ vars.AWS_REGION }} |
                  docker login --username AWS  --password-stdin ${{ steps.login-to-store-credentials.outputs.registry }}

                  docker pull ${{ steps.login-to-store-credentials.outputs.registry }}/${{ vars.BACKEND_ECR_REPOSITORY }}:latest

                  docker run --rm --env-file /home/ubuntu/backend.env ${{ steps.login-to-store-credentials.outputs.registry }}/${{ vars.BACKEND_ECR_REPOSITORY }}:latest alembic upgrade head

                  docker stop equity-lens-backend || true
                  docker rm equity-lens-backend || true

                  docker run -d --name equity-lens-backend -p 8000:8000 --env-file /home/ubuntu/backend.env ${{ steps.login-to-store-credentials.outputs.registry }}/${{ vars.BACKEND_ECR_REPOSITORY }}:latest



            



    